[tool.poetry]
name = "music-audiolyser"
version = "0.1.0"
description = "School project focused on analyzing song features to train models such as KNN."
authors = ["Your Name <you@example.com>"]
readme = "README.md"
license = "GPL-3.0-or-later"
packages = [{ include = "music_audiolyser", from = "src" }]

[tool.poetry.dependencies]
python = "3.9.18"
customtkinter = "^5.2.2"
essentia-tensorflow = "2.1b6.dev1110"
numpy = "1.26.4"
yt-dlp = "2025.3.26"
pandas = "^2.3.2"
pillow = "^11.3.0"
scikit-learn = "1.6.1"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
pytest = "^8.4.1"
isort = "^6.0.1"
pre-commit = "^4.3.0"
flake8 = "6.1.0"
pytest-cov = "^6.2.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true

[tool.poetry.scripts]
audiolyser = "music_audiolyser.main:run"