# Generated by Django 4.2.20 on 2026-05-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("genre", models.TextField()),
                ("bpm", models.IntegerField()),
                ("danceability", models.FloatField()),
                ("key", models.CharField(max_length=3)),
                ("scale", models.CharField(choices=[("minor", "Minor"), ("major", "Major")], max_length=5)),
                ("mood", models.TextField()),
                ("listeners", models.ManyToManyField(related_name="songs", to="music_app.student")),
            ],
        ),
    ]
