# Generated by Django 4.2.20 on 2026-05-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("youtube_id", models.CharField(max_length=11, unique=True)),
                ("title", models.CharField(default="", max_length=100)),
                ("artist", models.CharField(default="", max_length=100)),
                ("genre", models.TextField(default="")),
                ("bpm", models.IntegerField(default=0)),
                ("danceability", models.FloatField(default=0.0)),
                ("key", models.CharField(default="", max_length=3)),
                ("scale", models.CharField(choices=[("minor", "Minor"), ("major", "Major")], default="", max_length=5)),
                ("mood", models.TextField(default="")),
                ("listeners", models.ManyToManyField(related_name="songs", to="music_app.student")),
            ],
        ),
    ]
