# Generated by Django 4.2.20 on 2026-05-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="name",
        ),
        migrations.AddField(
            model_name="song",
            name="youtube_id",
            field=models.CharField(default="lol", max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
