name: Music Audiolyser CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.18
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Lint
        run: poetry run flake8 .
      - name: Format check
        run: poetry run black --check .
      - name: Run tests
        run: poetry run pytest
        - name: Run tests with coverage
        run: |
          poetry run pytest --cov=core --cov-report xml
      - name: Generate dynamic badge
        id: coverage_badge
        uses: Schneegans/dynamic-badges-action@v1.7.0
        with:
          label: Coverage
          message: ${{ steps.test.outputs.coverage }}
          color: ${{ steps.test.outputs.coverage_color }}
